#+TITLE: Guilherme G. Schardong
#+AUTHOR: Guilherme G Schardong
#+DATE: 2021-03-31
#+startup: hideblocks
#+options: num:nil
#+html_head: <meta name="referrer" content="origin">
#+html_head: <link rel="stylesheet" href="css/stylesheet.css" type="text/css">
#+html: <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'/>
#+html: <div class="hide-small" id="contact"><tt>guilherme[dot]schardong[at]isr[dot]uc[dot]pt</tt></div>
#+html: <div class="hide-small" id="pgpkey"><a href="res/key.txt"><tt>6EF2 6885 8BD4 F608 58AF 4763 BC05 5498 F7E7 7E74</tt></a></div>

* About
I'm currently a post-doctoral fellow at [[https://www.isr.uc.pt/][Institute for Systems an Robotics, University of Coimbra]], where I work on projects with the Portuguese Mint. Up to January 2022, I was a research fellow at GALGOS/PUC-Rio, with experience on oil&gas industry from projects with PETROBRAS on well-testing and reservoir model inference. I'm also a part-time post-doc at [[https://www.visgraf.impa.br/home/][Visgraf/IMPA]], where I work on computer graphics and machine learning, with emphasis on implicit function reconstruction and rendering.

* Background
I got my Bachelor's degree in Computer Science from UFSM in 2012 and a Master's degree in Informatics in the same university, in 2014, advised by prof. [[http://www.inf.ufsm.br/~pozzer][Cesar Pozzer]]. In 2018 I got my D.Sc. in Informatics at PUC-Rio, as a member of GALGOS. From 2014 to 2016 I worked as a developer under prof. [[http://www.inf.puc-rio.br/~celes][Waldemar Celes]] on the Reservoir Visualization group on Tecgraf/PUC-Rio Institute. In 2016 I started working with prof. [[https://www.inf.puc-rio.br/~lopes][Hélio Lopes]] (being advised by him since 2015) and was co-advised by prof. [[https://www.inf.puc-rio.br/~simone][Simone Barbosa]] during my doctorate. I'm currently a post-doctoral fellow at the Institute for Systems an Robotics, University of Coimbra at the [[https://visteam.isr.uc.pt/home][Computer Vision]] group, led by prof [[https://home.deec.uc.pt/~nunogon/][Nuno Gonçalves]]. I'm also a part-time post-doc collaborator, supervised by prof. [[https://www.impa.br/~lvelho][Luiz Velho]] from Visgraf/IMPA and prof. Hélio Lopes.

* Research
My current research interests involve mainly implicit function reconstruction using machine learning techniques. The idea is to explore differential properties inherent to the function and learning model used to speed-up the process, or increase its precision. Below is a selected list of publications from the last 5 years.

** Publications
- Schirmer L, *Schardong G*, da Silva V, et al. Neural Networks for Implicit Representations of 3D Scenes. In: Paiva A, Menotti D, Baranoski GVG, et al., eds. Proceedings of the 34th Conference on Graphics, Patterns and Images (SIBGRAPI). IEEE Computer Society; 2021.
- Grosman, J. S., Furtado, P. H. T., Rodrigues, A. M. B., *Schardong, G. G.*, Barbosa, S. D. J., & Lopes, H. C. V. (2020). Eras: Improving the quality control in the annotation process for Natural Language Processing tasks. Information Systems, 93, 101553. https://doi.org/10.1016/j.is.2020.101553
- Guimaraes, C. S., Schirmer, L., *Schardong, G.*, Barreto, A. B., & Lopes, H. (2020). Incorporating Dynamic Production-Logging Data to the Permeability-Estimation Workflow Using Machine Learning. SPE Journal, 25(05), 2765–2777. https://doi.org/10.2118/198954-PA
- Ribeiro, P. C., *Schardong, G. G.*, Barbosa, S. D. J., de Souza, C. S., & Lopes, H. (2019). Visual exploration of an ensemble of classifiers. Computers & Graphics, 85, 23–41. https://doi.org/10.1016/j.cag.2019.08.012
- González, S. F., Schirmer, L., Campagnolo, L. Q., Rodrigues, A. M. B., *Schardong, G. G.*, França, R., Lana, M., Barbosa, G. D. J., Barbosa, S. D. J., Poggi, M., & Lopes, H. (2019). Visual Filtering Tools and Analysis of Case Groups for Process Discovery. In Lecture Notes in Business Information Processing (Vol. 363, pp. 303–323). https://doi.org/10.1007/978-3-030-26169-6_15
- *Schardong, G. G.*, Rodrigues, A. M. B., Barbosa, S. D. J., & Lopes, H. (2018). Visual interactive support for selecting scenarios from time-series ensembles. Decision Support Systems, 113, 99–107. https://doi.org/10.1016/j.dss.2018.08.001
