#+TITLE: Neural Implicit Surface Evolution
#+AUTHOR: Tiago Novello, Vinícius da Silva, *Guilherme Schardong*, Luiz Schirmer, Hélio Lopes, Luiz Velho
#+VENUE: Proceedings of the IEEE/International Conference on Computer Vision, 2023
#+SETUPFILE: ../setup.org
#+html_head: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />
#+EXPORT_DATE: 2023-10-04
#+DOI: 10.1109/iccv51070.2023.01313

#+begin_teaser
file:../../res/smoothing-arm-curvatures.png
#+end_teaser

* Abstract
This work investigates the use of smooth neural networks for modeling dynamic variations of implicit surfaces under the level set equation (LSE). For this, it extends the representation of neural implicit surfaces to the space-time, which opens up mechanisms for continuous geometric transformations. Examples include evolving an initial surface towards general vector fields, smoothing and sharpening using the mean curvature equation, and interpolations of initial conditions. The network training considers two constraints. A data term is responsible for fitting the initial condition to the corresponding time instant. Then, a LSE term forces the network to approximate the underlying geometric evolution given by the LSE, without any supervision. The network can also be initialized based on previously trained initial conditions, resulting in faster convergence compared to the standard approach.
